= Creating a Hosted Cluster on OpenShift Virtualization

You can use the hosted control plane command line interface, `hcp``, to create an *OpenShift Container Platform hosted cluster*. The hosted cluster is automatically imported as a managed cluster.

== Prerequisites

oc patch ingresscontroller -n openshift-ingress-operator default --type=json -p '[{ "op": "add", "path": "/spec/routeAdmission", "value": {wildcardPolicy: "WildcardsAllowed"}}]'


== Install CLI

. Connect to the bastion host
+
[source,bash]
----
[lab-user@hypervisor ~]$ sudo ssh root@192.168.123.100
----

. Login to OCP
+
[source,bash]
----
[root@ocp4-bastion ~]# oc login {ocp_api}:6443 --username={ocp_username} --password={ocp_password}
----


. Download the cli called `hcp`
+
[source,bash]
----
[root@ocp4-bastion ~]# curl -O https://hcp-cli-download-multicluster-engine.apps.{guid}.dynamic.redhatworkshops.io/linux/amd64/hcp.tar.gz
----

. Extract the client
+
[source,bash]
----
[root@ocp4-bastion ~]# tar xvfz hcp.tar.gz -C /usr/local/bin/
----

. Confirm the command `hcp` is available 
+
[source,bash]
----
[root@ocp4-bastion ~]# hcp -v
----
+
.Sample Output
+
[%nowrap]
----
hcp version openshift/hypershift: e87182ca75da37c74b371aa0f17aeaa41437561a. Latest supported OCP: 4.14.0
----


[#create]
== Create Hosted Cluster

Some considerations:

* Run the hub cluster and workers on the same platform for hosted control planes.
* Each hosted cluster must have a unique name in order for multicluster engine operator to manage it.
* A hosted cluster cannot be created in the namespace of a multicluster engine operator managed cluster.

TODO: login or generate .kube/config because of the new TLS

. Create a new hosted cluster using the command `hcp`
+
[source,bash]
----
[root@ocp4-bastion ~]# hcp create cluster kubevirt \
--name cluster1 \
--release-image quay.io/openshift-release-dev/ocp-release:4.14.1-x86_64 \
--node-pool-replicas 2 \
--pull-secret ~/pull-secret.json \
--memory 6Gi \
--cores 2
----
+
.Sample Output
+
[%nowrap]
----
2023-12-02T21:49:55Z    INFO    Applied Kube resource   {"kind": "Namespace", "namespace": "", "name": "clusters"}
2023-12-02T21:49:55Z    INFO    Applied Kube resource   {"kind": "Secret", "namespace": "clusters", "name": "cluster1-pull-secret"}
2023-12-02T21:49:55Z    INFO    Applied Kube resource   {"kind": "", "namespace": "clusters", "name": "cluster1"}
2023-12-02T21:49:55Z    INFO    Applied Kube resource   {"kind": "Secret", "namespace": "clusters", "name": "cluster1-etcd-encryption-key"}
2023-12-02T21:49:55Z    INFO    Applied Kube resource   {"kind": "NodePool", "namespace": "clusters", "name": "cluster1"}
----
+
[NOTE]
You can use the `--release-image`` flag to set up the hosted cluster with a specific OpenShift Container Platform release.
+
A default node pool is created for the cluster with two virtual machine worker replicas according to the `--node-pool-replicas` flag.

. Verify the host control plane pods running inside of the new namespace created (`clusters-cluster1`)
+
[%nowrap]
----
[root@ocp4-bastion ~]# oc get pod -n clusters-cluster1
----
+
.Sample Output
+
[%nowrap]
----
NAME                                      READY   STATUS    RESTARTS   AGE
capi-provider-554c58b965-6cx78            1/1     Running   0          4m23s
cluster-api-5f5b78d889-2tnqm              1/1     Running   0          4m24s
control-plane-operator-67b7d4556b-4b4mq   1/1     Running   0          4m23s
----

. Check the status of the host clusters, querying the _Custom Resource_ named `HostedCluster`. 
+
[%nowrap]
----
[root@ocp4-bastion ~]# oc get --namespace clusters hostedclusters
----
+
.Sample Output
+
[%nowrap]
----
NAME       VERSION   KUBECONFIG                  PROGRESS    AVAILABLE   PROGRESSING   MESSAGE
cluster1   4.14.1    cluster1-admin-kubeconfig   Completed   True        False         The hosted control plane is available
----
+
[IMPORTANT]
It takes some minutes till the cluster switches from Partial to Completes

TODO:

Check status on ACM

hcp create kubeconfig --name cluster1 > cluster1-kubeconfig

oc get co --kubeconfig=cluster1-kubeconfig

Go to ACM, reveal credentials, connect to cluster

Review cluster