= Introduction



[#hcp]
== Hosted Control Planes

With _multicluster engine operator cluster management_, you can deploy *OpenShift Container Platform* clusters by using two different control plane configurations: *standalone* or *hosted control planes*:

* The *standalone* configuration uses dedicated virtual machines or physical machines to host the OpenShift Container Platform control plane. 

* With *hosted control planes* for *OpenShift Container Platform*, you create _control planes_ as _pods_ on a _hosting cluster_ without the need for dedicated physical machines for each control plane.

*Hosted control planes for OpenShift Container Platform* are available on bare metal and *Red Hat OpenShift Virtualization*, and as a _Technology Preview_ feature on _Amazon Web Services_ (_AWS_). You can host the _control planes_ on *OpenShift Container Platform version 4.14*. The *hosted control planes* feature is enabled by default.

The following table indicates which versions are supported for each platform:

[cols="1,1,1"]
|===
|Platform |Hosting HCP version|Minium hosted OCP version

|Bare metal
|4.14
|4.14

|Red Hat OpenShift Virtualization
|4.14
|4.14

|AWS (Technology Preview)
|4.11 - 4.14
|4.14
|===

The _control plane_ runs as pods that are contained in a single namespace and is associated with the *hosted control plane cluster*. When *OpenShift Container Platform* creates this type of hosted cluster, it creates a _worker node_ that is independent of the _control plane_.

*Hosted control plane clusters* offer several advantages:

* Saves cost by removing the need to host dedicated control plane nodes
* Introduces separation between the _control plane_ and the _workloads_, which improves isolation and reduces configuration errors that can require changes
* Decreases the cluster creation time by removing the requirement for control plane node bootstrapping
* Supports turn-key deployments or fully customized *OpenShift Container Platform* provisioning

[#acm]
== Red Hat Advanced Cluster Management for Kubernetes

*Red Hat® Advanced Cluster Management for Kubernetes* controls clusters and applications from a single console, with built-in security policies. Extend the value of *Red Hat OpenShift* by deploying apps, managing multiple clusters, and enforcing policies across multiple clusters at scale. Red Hat's solution ensures compliance, monitors usage, and maintains consistency.

TODO


[#ocpv]
== OpenShift Virtualization
*OpenShift Virtualization* is an add-on to *OpenShift Container Platform* that allows you to run and manage virtual machine workloads alongside container workloads.

*OpenShift Virtualization* adds new objects into your *OpenShift Container Platform* cluster by using _Kubernetes custom resources_ to enable virtualization tasks. These tasks include:

* Creating and managing Linux and Windows virtual machines (VMs)

* Running pod and VM workloads alongside each other in a cluster

* Connecting to virtual machines through a variety of consoles and CLI tools

* Importing and cloning existing virtual machines

* Managing network interface controllers and storage disks attached to virtual machines

* Live migrating virtual machines between nodes

An enhanced web console provides a graphical portal to manage these virtualized resources alongside the *OpenShift Container Platform* cluster containers and infrastructure.

*OpenShift Virtualization* is designed and tested to work well with *Red Hat OpenShift Data Foundation* features.

[#prerequisites]

== Prerequisites
TODO

[#metallb]

== MetalLB 
TODO